#!/usr/bin/env python3

import argparse
import socket
import sys

parser = argparse.ArgumentParser(description='''
Find a free port.
''')
parser.parse_args()

try:
    s=socket.socket()
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("", 0))
    print(s.getsockname()[1])
    s.close()
except:
    print("Reply hazy. Try again later.", file=sys.stderr)
    exit(1)
