#!/usr/bin/env python3

import argparse
import socket

parser = argparse.ArgumentParser(description='''
Find a free port.
''')
parser.parse_args()

s=socket.socket()
s.bind(("", 0))
print(s.getsockname()[1])
s.close()
